import type { Transaction } from './types';

function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export const mockTransactions: Transaction[] = [
  {
    id: 'transaction-1',
    type: 'expense',
    date: daysAgo(0),
    note: '',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-0',
    amount: 850,
  },
  {
    id: 'transaction-2',
    type: 'expense',
    date: daysAgo(0),
    note: 'Метро',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-1',
    amount: 120,
  },
  {
    id: 'transaction-3',
    type: 'expense',
    date: daysAgo(1),
    note: '',
    accountId: 'account-cash-usd',
    categoryId: 'category-expense-0',
    amount: 32,
  },
  {
    id: 'transaction-4',
    type: 'expense',
    date: daysAgo(2),
    note: '',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-2',
    amount: 3400,
  },
  {
    id: 'transaction-5',
    type: 'income',
    date: daysAgo(3),
    note: 'Аванс',
    accountId: 'account-card-rub',
    categoryId: 'category-income-0',
    amount: 60000,
  },
  {
    id: 'transaction-6',
    type: 'expense',
    date: daysAgo(4),
    note: '',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-3',
    amount: 28000,
  },
  {
    id: 'transaction-7',
    type: 'transfer',
    date: daysAgo(5),
    note: '',
    fromAccountId: 'account-card-rub',
    toAccountId: 'account-cash-usd',
    fromAmount: 9000,
    toAmount: 100,
  },
  {
    id: 'transaction-8',
    type: 'expense',
    date: daysAgo(7),
    note: '',
    accountId: 'account-cash-usd',
    categoryId: 'category-expense-4',
    amount: 18,
  },
  {
    id: 'transaction-9',
    type: 'expense',
    date: daysAgo(10),
    note: '',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-0',
    amount: 640,
  },
  {
    id: 'transaction-10',
    type: 'expense',
    date: daysAgo(12),
    note: 'Подписки за месяц',
    accountId: 'account-card-rub',
    categoryId: 'category-expense-6',
    amount: 999,
  },
  {
    id: 'transaction-11',
    type: 'income',
    date: daysAgo(2),
    note: 'Кэшбэк за покупки',
    accountId: 'account-card-rub',
    categoryId: 'category-income-4',
    amount: 340,
  },
  {
    id: 'transaction-12',
    type: 'income',
    date: daysAgo(6),
    note: 'Проект на фрилансе',
    accountId: 'account-card-rub',
    categoryId: 'category-income-1',
    amount: 45000,
  },
  {
    id: 'transaction-13',
    type: 'income',
    date: daysAgo(9),
    note: 'На день рождения',
    accountId: 'account-cash-usd',
    categoryId: 'category-income-2',
    amount: 100,
  },
  {
    id: 'transaction-14',
    type: 'income',
    date: daysAgo(14),
    note: 'Дивиденды по акциям',
    accountId: 'account-cash-usd',
    categoryId: 'category-income-3',
    amount: 85,
  },
  {
    id: 'transaction-15',
    type: 'income',
    date: daysAgo(18),
    note: 'Зарплата',
    accountId: 'account-card-rub',
    categoryId: 'category-income-0',
    amount: 95000,
  },
  {
    id: 'transaction-16',
    type: 'income',
    date: daysAgo(20),
    note: 'Аренда квартиры',
    accountId: 'account-card-rub',
    categoryId: 'category-income-5',
    amount: 32000,
  },
];
